#week 10
#Python Try-Except

try:
    print(x)
except:
    print('Error')

#Finally
try:
    print(x)
except:
    print("somthing went worng")
finally:
    print("the 'ty except' is finished")  